title: "George Preece"
description: "A blog on software architecture, development and security"
links:
  - GitHub:
    label: "github.com/georgepreece"
    value: "https://github.com/georgepreece"
  - LinkedIn:
    label: "linkedin.com/in/georgepreece"
    value: "https://linkedin.com/in/georgepreece"
biography: >
  I am a London-based Software Architect/Engineer with a passion for designing 
  and building enterprise-level applications. My interests also extend to 
  development methodologies and practices. Really, I just like to see teams 
  efficiently and optimally delivering high-quality software. I started this 
  blog to document and share the crucial lessons I have learned over the years.
permalink: /:categories/:title