title: "George Preece"
description: "A blog on software architecture, development and security"
links:
  - GitHub:
    label: "github.com/georgepreece"
    value: "https://github.com/georgepreece"
  - LinkedIn:
    label: "linkedin.com/in/georgepreece"
    value: "https://linkedin.com/in/georgepreece"
biography: >
  Welcome to my blog on software architecture, development and security! 
  I&apos;m a software engineer passionate about designing &amp; building 
  enterprise applications with a particular interest in development 
  methodologies and practices. I started this blog to document and share the 
  knowledge I have accumulated over the years and hope you find a use for it 
  just as I have.
permalink: /:categories/:title