title: "George Preece"
description: "A blog on software architecture, development and security"
links:
  - GitHub:
    label: "github.com/georgepreece"
    value: "https://github.com/georgepreece"
  - LinkedIn:
    label: "linkedin.com/in/georgepreece"
    value: "https://linkedin.com/in/georgepreece"
biography: >
  I'm George Preece; a software engineer with a passion for designing &amp;
  building enterprise applications. I started this blog to document and share
  what I have learned over the years and hope that you will find as much use
  reading my posts as I find writing them!
permalink: /:title